
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matataba
 */
public class CinemaUpdator extends javax.swing.JFrame {

    /**
     * Creates new form CinemaUpdator
     */
    String select="";
    String data11="";int limit=0;
    public CinemaUpdator() {initComponents();
        buttonGroup1.add(hd4);
        buttonGroup1.add(d7);
              try {
            nix();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(request.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
public void nix() throws FileNotFoundException{
        
          Scanner sc= new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\cinema#.txt"));
      
         
                while(sc.hasNextLine()){
             String line=sc.nextLine();
             Scanner sline = new Scanner(line);
             while(sline.hasNext()){
             String data=sline.next();
             int getter=sline.nextInt();
             String a=sline.next();
             String a1=sline.next();
            limit=getter;
        
             } 
            }

        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cinema = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        hd2 = new javax.swing.JRadioButton();
        d5 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        hd4 = new javax.swing.JRadioButton();
        d7 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        q = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jButton7.setText("Assign");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("Select Cinema:");

        cinema.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        cinema.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cinema.setText("1");
        cinema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinemaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 204, 204));
        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MovieMax!"));

        hd2.setText("HD");
        hd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd2ActionPerformed(evt);
            }
        });

        d5.setText("3D");
        d5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d5ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Movie:");

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 238, Short.MAX_VALUE)
                        .addComponent(hd2)
                        .addGap(70, 70, 70)
                        .addComponent(d5)
                        .addGap(85, 85, 85))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hd2)
                    .addComponent(d5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 0, 11)); // NOI18N
        jButton2.setText("-");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(5, 5, 33));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MovieMax!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        hd4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        hd4.setForeground(new java.awt.Color(255, 255, 255));
        hd4.setText("HD");
        hd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hd4ActionPerformed(evt);
            }
        });

        d7.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        d7.setForeground(new java.awt.Color(255, 255, 255));
        d7.setText("3D");
        d7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d7ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Select Cinema:");

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Item" }));
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 153, 0));
        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 153, 0));
        jButton11.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 153, 0));
        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Select Movie:");

        q.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        q.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        q.setText("1");

        jButton5.setBackground(new java.awt.Color(255, 153, 0));
        jButton5.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("ZOMBIE", 1, 40)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cinema Update");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(hd4)
                                .addGap(18, 18, 18)
                                .addComponent(d7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d7)
                    .addComponent(hd4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String q=cinema.getText();
        try {String content="";
            int counter=0;
            Scanner sc = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt"));
            if(data11.equals("Select Item")||select.equals("")){counter++;
                JOptionPane.showMessageDialog(null,"ERROR");
            }
            else{while(sc.hasNextLine()){

                String line=sc.nextLine();
                Scanner sline = new Scanner(line);

                while(sline.hasNext()){
                    String data=sline.next();
                    String data1=sline.next();
                    String data2=sline.next();
                    String data3=sline.next();
                    String data4=sline.next();
                    String c=sline.next();

                    if(data11.equals(data2)&&data1.equals(select) &&c.equals("UA")){counter++;
                        line=data+" "+data1+" "+data2+" "+data3+" "+data4+" C"+q;
                        JOptionPane.showMessageDialog(null,"The movie is now Assigned to Cinema "+q);
                    }
                    content=content+line+"\n";
                }

            }
            if(counter==0){
                JOptionPane.showMessageDialog(null,"The movie already had a cenima!");
                counter--;
            }
            sc.close();
            FileWriter writer = null;
            try {
                writer = new FileWriter("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt");
            } catch (IOException ex) {
                Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
            }
            writer.write(content);
            writer.close(); }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(CinemaAs.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CinemaAs.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cinemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinemaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String q=cinema.getText();
        if((Integer.parseInt(q))<=1){
            JOptionPane.showMessageDialog(null,"Cinema Cannot be set to less than 0");
        }
        else{
            cinema.setText(String.valueOf((Integer.parseInt(q))-1));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String q=cinema.getText();
        if((Integer.parseInt(q))==9){
            JOptionPane.showMessageDialog(null,"We only have 9 Cinema.");
        }
        else{
            cinema.setText(String.valueOf((Integer.parseInt(q))+1));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd2ActionPerformed
        combo.removeAllItems(); if(hd2.isSelected()){
            select=hd2.getText();

            Scanner sc;
            try {
                sc = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt"));

                while(sc.hasNextLine()){
                    String line=sc.nextLine();
                    Scanner sline = new Scanner(line);
                    while(sline.hasNext()){
                        String data=sline.next();
                        String data1=sline.next();
                        String data2=sline.next();
                        String data3=sline.next();
                        String data4=sline.next();
                        String c=sline.next();
                        if(data1.equals("HD")){
                            combo.addItem(data2);
                            data11=""+combo.getSelectedItem();

                        }
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_hd2ActionPerformed

    private void d5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d5ActionPerformed
        combo.removeAllItems();
        if(d5.isSelected()){

            select=d5.getText();
            Scanner sc;
            try {
                sc = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt"));

                while(sc.hasNextLine()){
                    String line=sc.nextLine();
                    Scanner sline = new Scanner(line);
                    while(sline.hasNext()){
                        String data=sline.next();
                        String data1=sline.next();
                        String data2=sline.next();
                        String data3=sline.next();
                        String data4=sline.next();
                        String c=sline.next();
                        if(data1.equals("3D")){
                            combo.addItem(data2);
                            data11=""+combo.getSelectedItem();

                        }
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(delete.class.getName()).log(Level.SEVERE, null, ex);
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_d5ActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        data11=(String) combo.getSelectedItem();
    }//GEN-LAST:event_comboActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new MovieManagement().setVisible(true);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String q=cinema.getText();
        if((Integer.parseInt(q))<=1){
            JOptionPane.showMessageDialog(null,"Cinema Cannot be set to less than 0");
        }
        else{
            cinema.setText(String.valueOf((Integer.parseInt(q))-1));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void hd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hd4ActionPerformed
        combo2.removeAllItems(); if(hd4.isSelected()){
            select=hd4.getText();

            Scanner sc;
            try {
                sc = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt"));

                while(sc.hasNextLine()){
                    String line=sc.nextLine();
                    Scanner sline = new Scanner(line);
                    while(sline.hasNext()){
                        String data=sline.next();
                        String data1=sline.next();
                        String data2=sline.next();
                        String data3=sline.next();
                        String data4=sline.next();
                        String c=sline.next();
                        if(data.equals("Available")&&data1.equals("HD")){
                            combo2.addItem(data2);
                            data11=""+combo2.getSelectedItem();

                        }
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_hd4ActionPerformed

    private void d7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d7ActionPerformed
        combo2.removeAllItems();
        if(d7.isSelected()){

            select=d7.getText();
            Scanner sc;
            try {
                sc = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt"));

                while(sc.hasNextLine()){
                    String line=sc.nextLine();
                    Scanner sline = new Scanner(line);
                    while(sline.hasNext()){
                        String data=sline.next();
                        String data1=sline.next();
                        String data2=sline.next();
                        String data3=sline.next();
                        String data4=sline.next();
                        String c=sline.next();
                        if(data.equals("Available")&&data1.equals("3D")){
                            combo2.addItem(data2);
                            data11=""+combo2.getSelectedItem();

                        }
                    }
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CinemaUpdator.class.getName()).log(Level.SEVERE, null, ex);
            }
        }          // TODO add your handling code here:
    }//GEN-LAST:event_d7ActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        data11=(String) combo2.getSelectedItem();
    }//GEN-LAST:event_combo2ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String cinema=q.getText();String holder="";            
           try {
           Scanner sc1 = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\cinema#.txt"));
       
        while(sc1.hasNextLine()){
                 
                 String line=sc1.nextLine();
                 Scanner sline = new Scanner(line);
                 
                 
                 while(sline.hasNext()){
                     String data=sline.next();
                     String data1=sline.next();
                     String data2=sline.next();
                     String data3=sline.next();
                     if(cinema.equals(data1)){
                         holder=data3;
                     }
                 }
        }  } catch (FileNotFoundException ex) {
             Logger.getLogger(CinemaAs.class.getName()).log(Level.SEVERE, null, ex);
         }  try {String content="";
         int counter=0;
        
             Scanner sc = new Scanner(new FileReader("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt"));
           if(data11.equals("Select Item")||select.equals("")){counter++;
               JOptionPane.showMessageDialog(null,"ERROR"); 
           }
             else{while(sc.hasNextLine()){
                 
                 String line=sc.nextLine();
                 Scanner sline = new Scanner(line);
                 
                 
                 while(sline.hasNext()){
                     String data=sline.next();
                     String data1=sline.next();
                     String data2=sline.next();
                     String data3=sline.next();
                     String data4=sline.next();
                     String c=sline.next();
                     
                     if(data.equals("Available")&&data11.equals(data2)&&data1.equals(select) &&!c.equals("UA")){counter++;
                         
                     if(c.equals("C"+cinema)){
                         JOptionPane.showMessageDialog(null,"Must Assign to new one. "); 
                     }else{
          
                     line=data+" "+data1+" "+data2+" "+data3+" "+holder+" C"+cinema;
                            JOptionPane.showMessageDialog(null,"The movie is now Assigned to Cinema "+cinema); 
                     }
                     }
                     content=content+line+"\n";
                 }
         
             } 
             if(counter==0){
                  JOptionPane.showMessageDialog(null,"The movie must be Assigned FIRST!"); 
                  counter--;
             }
             sc.close();
                FileWriter writer = null;
                  try {
                      writer = new FileWriter("C:\\Users\\Matataba\\Documents\\NetBeansProjects\\Flower_CS\\src\\movies.txt");
                  } catch (IOException ex) {
                      Logger.getLogger(edit.class.getName()).log(Level.SEVERE, null, ex);
                  }
                writer.write(content);
                writer.close(); }
         
          if(counter==0){
                  JOptionPane.showMessageDialog(null,"The movie need to assign first!"); 
                  counter--;
             }
         } catch (FileNotFoundException ex) {
             Logger.getLogger(CinemaAs.class.getName()).log(Level.SEVERE, null, ex);
         } catch (IOException ex) {
             Logger.getLogger(CinemaAs.class.getName()).log(Level.SEVERE, null, ex);
         }
 
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
   new CinemaManagement().setVisible(true);
        setVisible(false);        }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      String cinema=q.getText();
        if((Integer.parseInt(cinema))<=1){
             JOptionPane.showMessageDialog(null,"Cinema Cannot be set to less than 0"); 
        }
        else{
              q.setText(String.valueOf((Integer.parseInt(cinema))-1));
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      String cinema=q.getText();
        if((Integer.parseInt(cinema))==limit){
              JOptionPane.showMessageDialog(null,"We only have "+limit+" Cinema."); 
        }
        else{
              q.setText(String.valueOf((Integer.parseInt(cinema))+1));
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CinemaUpdator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CinemaUpdator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CinemaUpdator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CinemaUpdator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CinemaUpdator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cinema;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JRadioButton d5;
    private javax.swing.JRadioButton d7;
    private javax.swing.JRadioButton hd2;
    private javax.swing.JRadioButton hd4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField q;
    // End of variables declaration//GEN-END:variables
}
